version = 1

test_patterns = [
  ".test/**/*.cs",
  ".tests/**/*.cs"
]

exclude_patterns = [
  "zzsc/**/*",
  "zzio_cli/**/*",
  "zzio_dbsqlite/**/*",
  "Veldrid.ImGui/**/*"
]

[[analyzers]]
name = "csharp"
enabled = true
